name: Main Workflow
on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: Due Dates
        uses: alexleventer/github-issue-due-dates-action@1.0.9
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
